server:
  port: 8080
spring:
  redis:
    port: 6379
    hostName: 192.168.201.130
    password: 12345
    #连接池最大连接数（使用负值表示没有限制，但会造成阻塞，详见https://blog.csdn.net/johnson1013/article/details/82083400）
    maxTotal: 100
    #连接池中的最大空闲连接
    maxIdle: 6
    #连接池最大阻塞等待时间（使用负值表示没有限制）
    maxWaitMillis: 5000
    #Redis过期时间
    expiration: 60000
    testOnBorrow: false
    index: 11

